### ISSUE TITLE
bug: Failing build static page generation

### ISSUE THREAD

**Issue by CrazyWolf13** [homarr-labs/homarr#1090]
### Provide environment information

  System:
    OS: Linux 6.8 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
    Memory: 3.81 GB / 4.00 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.17.0 - /bin/node
    Yarn: 3.6.0 - /bin/yarn
    npm: 10.8.2 - /bin/npm

### Describe the bug

When I try to manually build this project, after updating I get the following error:
```
root@homarr:/opt/homarr# yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @mantine/core@npm:6.0.21 [bdc39] doesn't provide @emotion/react (p2634a), requested by @mantine/styles
➤ YN0002: │ @mantine/next@npm:6.0.21 [bdc39] doesn't provide @emotion/react (pf04a7), requested by @mantine/styles
➤ YN0002: │ @mantine/next@npm:6.0.21 [bdc39] doesn't provide @emotion/react (p9d76b), requested by @mantine/ssr
➤ YN0002: │ @mantine/next@npm:6.0.21 [bdc39] doesn't provide @emotion/server (pe0775), requested by @mantine/ssr
➤ YN0002: │ @nivo/annotations@npm:0.83.1 [6a2dc] doesn't provide react-dom (p04e08), requested by @react-spring/web
➤ YN0002: │ @nivo/axes@npm:0.83.1 [6a2dc] doesn't provide react-dom (pd019a), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.1 [6a2dc] doesn't provide react-dom (p896ad), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.1 [a6114] doesn't provide react-dom (p3766b), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.1 [bdc39] doesn't provide react-dom (p478c3), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.1 [da4e9] doesn't provide react-dom (pbc155), requested by @react-spring/web
➤ YN0002: │ @nivo/line@npm:0.83.1 [bdc39] doesn't provide react-dom (p46f9c), requested by @react-spring/web
➤ YN0002: │ @nivo/tooltip@npm:0.83.1 doesn't provide prop-types (p94058), requested by @nivo/core
➤ YN0002: │ @nivo/tooltip@npm:0.83.1 doesn't provide react (p3546e), requested by @react-spring/web
➤ YN0002: │ @nivo/tooltip@npm:0.83.1 doesn't provide react (p5bf6e), requested by @nivo/core
➤ YN0002: │ @nivo/tooltip@npm:0.83.1 doesn't provide react-dom (pf5853), requested by @react-spring/web
➤ YN0002: │ @nivo/voronoi@npm:0.83.1 [6a2dc] doesn't provide prop-types (p20baf), requested by @nivo/core
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.12 doesn't provide @tiptap/pm (p6560d), requested by @tiptap/core
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.12 doesn't provide @tiptap/pm (p1fe9b), requested by @tiptap/extension-code-block
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.12 doesn't provide @tiptap/pm (pda644), requested by @tiptap/extension-dropcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.12 doesn't provide @tiptap/pm (pa1b36), requested by @tiptap/extension-gapcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.12 doesn't provide @tiptap/pm (p6fff9), requested by @tiptap/extension-history
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.12 doesn't provide @tiptap/pm (p85123), requested by @tiptap/extension-horizontal-rule
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (pa4b89), requested by @tiptap/extension-color
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p4c47b), requested by @tiptap/extension-highlight
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p0cf40), requested by @tiptap/extension-image
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p17aca), requested by @tiptap/extension-link
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (pa5ef2), requested by @tiptap/extension-table-cell
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (pc1841), requested by @tiptap/extension-table-header
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (peac23), requested by @tiptap/extension-table-row
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p58f5e), requested by @tiptap/extension-table
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (pee198), requested by @tiptap/extension-task-item
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p4353c), requested by @tiptap/extension-task-list
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (paa6b2), requested by @tiptap/extension-text-align
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p50fe6), requested by @tiptap/extension-text-style
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p939b8), requested by @tiptap/extension-underline
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p3abb8), requested by @tiptap/react
➤ YN0060: │ homarr@workspace:. provides i18next (pd61c8) with version 22.5.1, which doesn't satisfy what next-i18next requests
➤ YN0002: │ homarr@workspace:. doesn't provide prop-types (p44d56), requested by @nivo/core
➤ YN0060: │ homarr@workspace:. provides react-i18next (pfec32) with version 12.3.1, which doesn't satisfy what next-i18next requests
➤ YN0002: │ homarr@workspace:. doesn't provide vite (pbf76b), requested by @vitejs/plugin-react
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 242ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 468ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 340ms
➤ YN0000: Done with warnings in 1s 123ms
root@homarr:/opt/homarr# yarn build
- info Loaded env from /opt/homarr/.env
- info Linting and checking validity of types ..- error ESLint: ESLint configuration in package.json is invalid:  - Unexpected top-level property "ignoreDuringBuilds".
- info Linting and checking validity of types
- info Creating an optimized production build
- info Compiled successfully
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization

- info Collecting page data
Static worker unexpectedly exited with code: null and signal: SIGTERM
Static worker unexpectedly exited with code: null and signal: SIGTERM
Static worker unexpectedly exited with code: null and signal: SIGTERM
- warn Restarted static page generation for /en/401 because it took more than 60 seconds
- warn See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
- warn Restarted static page generation for /ar/401 because it took more than 60 seconds
- warn Restarted static page generation for /cn/401 because it took more than 60 seconds
- warn Restarted static page generation for /cr/401 because it took more than 60 seconds
...........
- warn Restarted static page generation for /lt/404 because it took more than 60 seconds
- warn Restarted static page generation for /ro/404 because it took more than 60 seconds
Static worker unexpectedly exited with code: null and signal: SIGTERM
Static worker unexpectedly exited with code: null and signal: SIGTERM
Static worker unexpectedly exited with code: null and signal: SIGTERM
- warn Restarted static page generation for /en/401 because it took more than 60 seconds
- warn Restarted static page generation for /ar/401 because it took more than 60 seconds
.......
- warn Restarted static page generation for /et/404 because it took more than 60 seconds
- warn Restarted static page generation for /lt/404 because it took more than 60 seconds
- warn Restarted static page generation for /ro/404 because it took more than 60 seconds
Static worker unexpectedly exited with code: null and signal: SIGTERM
Static worker unexpectedly exited with code: null and signal: SIGTERM
Static worker unexpectedly exited with code: null and signal: SIGTERM

> Build error occurred
Error: Static page generation for /en/401 is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (/opt/homarr/node_modules/next/dist/build/index.js:697:39)
    at Worker.exportPage (/opt/homarr/node_modules/next/dist/lib/worker.js:88:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/homarr/node_modules/next/dist/export/index.js:519:32
    at async Span.traceAsyncFn (/opt/homarr/node_modules/next/dist/trace/trace.js:103:20)
    at async Promise.all (index 0)
    at async /opt/homarr/node_modules/next/dist/export/index.js:510:9
    at async Span.traceAsyncFn (/opt/homarr/node_modules/next/dist/trace/trace.js:103:20)
    at async /opt/homarr/node_modules/next/dist/build/index.js:1579:21
    at async Span.traceAsyncFn (/opt/homarr/node_modules/next/dist/trace/trace.js:103:20)
```

### Link to reproduction

?? Not sure what this means ?

### To reproduce

1. Install homarr via git
2. build
3. after a while a update gets released
4. I try to update
5. the build after update fails with the above error

I used the following commands to update:
```bash
systemctl stop homarr
cd /opt/homarr
if ! git pull; then
  echo "Already up to date."
  systemctl start homarr
  echo "No update required."
  exit
fi
yarn install
yarn build
systemctl start homarr
```

### Additional information

Thanks for looking into this :)

**Comment by Meierschlumpf** [comment]
@CrazyWolf13 is it possible that you meant to create an issue on [ajnart/homarr](https://github.com/ajnart/homarr)? This is us (the maintainers) working on the major 1.0 release

**Comment by CrazyWolf13** [comment]
Ohh I see, I'm really sorry!

Will create an issue on the other repo, thanks for the quick reply! :)

**Comment by Meierschlumpf** [comment]
No problem 😉

**Comment by CrazyWolf13** [comment]
For anyone else finding this, this is the issue on the main repo: https://github.com/ajnart/homarr/issues/2125
